---
- name: Download Jenkins repository key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
    state: present
    filename: jenkins
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Ensure Jenkins service directory exists
  file:
    path: /var/lib/jenkins
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Ensure Jenkins plugins directory exists
  file:
    path: /var/lib/jenkins/plugins
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Download Jenkins plugins
  get_url:
    url: "https://updates.jenkins.io/download/plugins/{{ item }}/latest/{{ item }}.hpi"
    dest: "/var/lib/jenkins/plugins/{{ item }}.hpi"
    owner: jenkins
    group: jenkins
    mode: '0644'
  with_items:
    - workflow-aggregator
    - git
    - github
    - sonar
    - pipeline-stage-view
    - junit
    - cobertura
    - warnings-ng
  notify: restart jenkins

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
