---
- name: Download Jenkins repository key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
    state: present
    filename: jenkins
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Create Jenkins directories
  file:
    path: "{{ item }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'
  with_items:
    - /var/lib/jenkins
    - /var/lib/jenkins/plugins
    - /var/cache/jenkins
    - /var/log/jenkins

- name: Configure Jenkins defaults
  template:
    src: jenkins.default.j2
    dest: /etc/default/jenkins
    owner: root
    group: root
    mode: '0644'
  notify: restart jenkins

- name: Configure Jenkins systemd service
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service
    owner: root
    group: root
    mode: '0644'
  notify: restart jenkins

- name: Ensure Jenkins service is enabled and started
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes

- name: Download Jenkins plugins
  get_url:
    url: "https://updates.jenkins.io/download/plugins/{{ item }}/latest/{{ item }}.hpi"
    dest: "/var/lib/jenkins/plugins/{{ item }}.hpi"
    owner: jenkins
    group: jenkins
    mode: '0644'
  with_items: "{{ jenkins_plugins }}"
  notify: restart jenkins

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
  register: jenkins_start
  ignore_errors: yes

- name: Debug Jenkins service status
  command: systemctl status jenkins
  register: jenkins_status
  ignore_errors: yes
  when: jenkins_start is failed

- name: Show Jenkins logs
  command: journalctl -u jenkins -n 50
  register: jenkins_logs
  ignore_errors: yes
  when: jenkins_start is failed

- name: Debug output
  debug:
    var: jenkins_logs.stdout_lines
  when: jenkins_start is failed
