---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - curl
    - wget
    - unzip
    - python3-pip
    - openjdk-11-jdk

- name: Set timezone
  timezone:
    name: UTC
