---
- name: Download SonarQube
  get_url:
    url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
    dest: "/opt/sonarqube-{{ sonarqube_version }}.zip"

- name: Create SonarQube group
  group:
    name: sonarqube
    state: present

- name: Create SonarQube user
  user:
    name: sonarqube
    group: sonarqube
    shell: /bin/bash
    system: yes

- name: Extract SonarQube
  unarchive:
    src: "/opt/sonarqube-{{ sonarqube_version }}.zip"
    dest: /opt
    remote_src: yes
    creates: "/opt/sonarqube-{{ sonarqube_version }}"

- name: Create SonarQube symlink
  file:
    src: "/opt/sonarqube-{{ sonarqube_version }}"
    dest: /opt/sonarqube
    state: link
    owner: sonarqube
    group: sonarqube

- name: Configure SonarQube service
  template:
    src: sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service
  notify: restart sonarqube
